Ac404 72 implement adding merchants
timjuic/paypro-android pull request #21
Opened 2023-12-20 15:28 UTC by mkljaic20

Adding merchants is fully connected to the backend, it now sends card types and status in correct format. Also replaced hardcoded JWT to function call so it works with the logged in user.

2023-12-21 08:38 UTC, timjuic requested changes
Implementation is okay, but some parts of code are not clear what they do. CardBrandType enum needs to be removed as this is exactly what backend returns. So please do that

2023-12-21 08:38 UTC, timjuic commented on app/src/main/java/com/Found404/paypro/ui/pages/CardPaymentsPage.kt
> +                        merchantModel.copy(cardTypes = merchantModel.cardTypes + CardBrandType.values().first { it.cardBrandId == cardType.cardBrandId })
I see that the hardcoded `CardBrandType` is still used here. Card brands received from the backend should only be used.  It is also not clear to me what this line does exactly

2023-12-21 08:38 UTC, timjuic commented on core/src/main/java/com/found404/core/models/CreditCardType.kt
> +}
This should be removed and cardbrands from the backend need to be used. It is enough to define CreditCardType here.

2023-12-23 16:48 UTC, jivancic20 approved these changes
All good, but make sure to refactor code whenever needed

2023-12-23 17:52 UTC, timjuic approved these changes

2023-12-23 20:32 UTC, aantonic20 approved these changes
All necessary corrections have already been identified and addressed. Remember to refactor the code once everything is completed.

2023-12-24 15:54 UTC, merged