Ac404 30 displaying terminals
timjuic/paypro-android pull request #25
Opened 2023-12-28 18:10 UTC by mkljaic20

Added screens for displaying merchants and deleting them. Created classes that connect to the backend and fetch the data.

2023-12-29 17:21 UTC, jivancic20 submitted a review, later dismissed
Looks good, nice job

2023-12-29 17:54 UTC, timjuic requested changes
Great job on the code. I only advise you to move mentioned functions to a separate files for better organization and readability.

Also it seems that this doesnt include the most recent code from develop, so there might be conflicts when merging

2023-12-29 17:54 UTC, timjuic commented on app/src/main/java/com/Found404/paypro/ui/pages/AddingMerchantsPage.kt
> +fun DeleteTerminalPopup(terminalId: String, onConfirm: () -> Unit, onCancel: () -> Unit) {
Please place this composable in separate file in order to keep this page cleaner. You put it in `components` and call it `DeleteTerminalModal` or `DeleteTerminalPopup`

2023-12-29 17:54 UTC, timjuic commented on app/src/main/java/com/Found404/paypro/ui/pages/AddingMerchantsPage.kt
> +fun MerchantItem(merchant: MerchantResponse, onDeleteTerminal: (String) -> Unit) {
MerchantItem can be moved to a separate component file.

2023-12-29 22:54 UTC, dominikn1 approved these changes, later dismissed
Looks good!

2024-01-01 15:55 UTC, timjuic approved these changes
Looks good now. Good job

2024-01-02 13:16 UTC, dominikn1 approved these changes
Changes look on point.

2024-01-02 14:07 UTC, merged