Ac404 26 deleting merchant
timjuic/paypro-android pull request #50
Opened 2024-01-28 19:34 UTC by dominikn1

Changed Surface component with Dialog in deleteMerchantPopup, made it to match rest of PayPro components.

2024-01-28 19:36 UTC, jivancic20 approved these changes

2024-01-28 19:50 UTC, aantonic20 approved these changes
Looks good.

2024-01-28 22:39 UTC, mkljaic20 approved these changes

2024-01-29 10:29 UTC, timjuic requested changes
It seems that in this branch there is a lot of old code that was changed on develop in the meantime. I suggest pulling changes from develop first and then commiting that.

2024-01-29 11:37 UTC, timjuic approved these changes

2024-01-29 11:37 UTC, merged