Ac404 26 deleting merchant
timjuic/paypro-android pull request #8
Opened 2023-12-15 11:13 UTC by dominikn1

I added DeletingMerchantPage inside app/ui module.

2023-12-15 11:17 UTC, mkljaic20 commented on app/src/main/java/com/Found404/paypro/ui/pages/DeletingMerchantPage.kt
> +
You should delete the empty space here so the good looks nicer

2023-12-15 11:18 UTC, mkljaic20 requested changes
You should delete an empty space left around line 80 in DeletingMerchantPage. Everything else looks good

2023-12-15 13:47 UTC, aantonic20 approved these changes, later dismissed
Everything looks good, nice work.

2023-12-15 15:56 UTC, timjuic requested changes
Its a solid looking page for deleting merchants. However, according to our app sketches this should be a modal window. There is no need for an extra page for this.

Here is how you could implement it as a modal window. I asked chatgpt to make it based on your existing code. https://chat.openai.com/share/d94fa9ba-11a5-4c40-bae8-067e01039e30

2023-12-15 19:34 UTC, jivancic20 approved these changes, later dismissed
@timjuic already covered any remark I had, so just fix what he already said.

2024-01-04 08:39 UTC, timjuic approved these changes, later dismissed
Deleting merchants appears to be working well now. Modal window and buttons look okay. It would be nice if you could just replace your inputField with our composable `PayProLabeledInput` Its single line and has already predefined styling.

There is 1 more thing that needs to be done here. And that is removing the merchant from the page that was just deleted. This could be done by just refreshing the merchant list. (getting it from the database again)

2024-01-04 08:39 UTC, timjuic commented on build.gradle.kts
Is there a reason why this was switched to 8.2.0? This might cause issues with other modules and code

2024-01-04 10:16 UTC, mkljaic20 submitted a review, later dismissed

2024-01-04 11:34 UTC, mkljaic20 approved these changes

2024-01-04 11:34 UTC, timjuic approved these changes

2024-01-04 11:34 UTC, merged